### ISSUE TITLE
Make Table of Content always visible

### ISSUE THREAD

**Issue by valencik** [planet42/Laika#338]
I'd like an option for the Table of Contents to always be visible.

Currently when the window is resized below some threshold the table of contents is hidden.
Ideally I'd like the table of contents to still be visible on smaller screens.

Perhaps on small/medium screens it could change to being visible above the main document content, as opposed to on the right?

_Edit:_
Maybe something like this? I don't know, I am not one with the design 😬 

<img width="1393" alt="Screen Shot 2022-12-06 at 8 40 39 PM" src="https://user-images.githubusercontent.com/5440389/206066876-30df414a-6fbe-4d7f-a465-9bf26e08e5fe.png">

**Comment by valencik** [comment]
I've had success with the following css:

```css
@media (max-width: 1450px) {
  #page-nav {
    display: block;
    position: static;
    background-color: transparent;
    margin-left: auto;
    width: 100%;
    max-width: var(--content-width);
    padding: 15px 45px 0px 45px;
    margin-right: auto;
  }
}
```

At time of writing, you can currently see this in action at : https://valencik.github.io/http4s/v0.23/docs/client.html

@jenshalm Would you be interested in this as a contribution to Laika's official css?
